CREATE TYPE "jawaban_siswa_question_type_enum" AS ENUM (
  'multiple_choice',
  'drag_drop'
);

CREATE TYPE "soal_drag_drop_drag_type_enum" AS ENUM (
  'ordering',
  'matching'
);

CREATE TYPE "test_session_status_enum" AS ENUM (
  'ongoing',
  'completed',
  'timeout'
);

CREATE TYPE "test_session_soal_question_type_enum" AS ENUM (
  'multiple_choice',
  'drag_drop'
);

CREATE TYPE "users_role_enum" AS ENUM (
  'siswa',
  'admin'
);

CREATE TABLE "drag_correct_answer" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_drag_item" int NOT NULL,
  "id_drag_slot" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "drag_item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_soal_drag_drop" int NOT NULL,
  "label" varchar(255) NOT NULL,
  "image_url" varchar(500) DEFAULT null,
  "urutan" smallint NOT NULL DEFAULT 1,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "drag_slot" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_soal_drag_drop" int NOT NULL,
  "label" varchar(255) NOT NULL,
  "image_url" varchar(500) DEFAULT null,
  "urutan" smallint NOT NULL DEFAULT 1,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "jawaban_siswa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_test_session_soal" int NOT NULL,
  "jawaban_dipilih" char(1) DEFAULT null,
  "question_type" jawaban_siswa_question_type_enum NOT NULL DEFAULT 'multiple_choice',
  "jawaban_drag_drop" json DEFAULT null,
  "is_correct" boolean NOT NULL DEFAULT false,
  "dijawab_pada" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "mata_pelajaran" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nama" varchar(50) NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "materi" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_mata_pelajaran" int NOT NULL,
  "id_tingkat" int NOT NULL,
  "nama" varchar(100) NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "default_durasi_menit" int NOT NULL DEFAULT 60,
  "default_jumlah_soal" int NOT NULL DEFAULT 20,
  "owner_user_id" int DEFAULT NULL,
  "school_id" int DEFAULT NULL,
  "labels" json DEFAULT '[]',
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "soal" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_materi" int NOT NULL,
  "id_tingkat" int NOT NULL,
  "pertanyaan" text NOT NULL,
  "opsi_a" varchar(500) NOT NULL,
  "opsi_b" varchar(500) NOT NULL,
  "opsi_c" varchar(500) NOT NULL,
  "opsi_d" varchar(500) NOT NULL,
  "jawaban_benar" char(1) NOT NULL,
  "pembahasan" text,
  "is_active" boolean NOT NULL DEFAULT true,
  "image_path" varchar(255) DEFAULT null,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "soal_drag_drop" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_materi" int NOT NULL,
  "id_tingkat" int NOT NULL,
  "pertanyaan" text NOT NULL,
  "drag_type" soal_drag_drop_drag_type_enum NOT NULL,
  "pembahasan" text,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "soal_drag_drop_gambar" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_soal_drag_drop" int NOT NULL,
  "nama_file" varchar(255) NOT NULL,
  "file_path" varchar(500) NOT NULL,
  "file_size" int NOT NULL,
  "mime_type" varchar(50) NOT NULL,
  "urutan" smallint NOT NULL DEFAULT 1,
  "keterangan" varchar(255) DEFAULT null,
  "cloud_id" varchar(255) DEFAULT null,
  "public_id" varchar(500) DEFAULT null,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "soal_gambar" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_soal" int NOT NULL,
  "nama_file" varchar(255) NOT NULL,
  "file_path" varchar(500) NOT NULL,
  "file_size" int NOT NULL,
  "mime_type" varchar(50) NOT NULL,
  "urutan" smallint NOT NULL DEFAULT 1,
  "keterangan" varchar(255) DEFAULT null,
  "cloud_id" varchar(255) DEFAULT null,
  "public_id" varchar(500) DEFAULT null,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "test_session" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "session_token" varchar(64) NOT NULL,
  "nama_peserta" varchar(100) NOT NULL,
  "id_tingkat" int NOT NULL,
  "id_mata_pelajaran" int NOT NULL,
  "user_id" int DEFAULT null,
  "waktu_mulai" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "waktu_selesai" timestamp DEFAULT null,
  "durasi_menit" int NOT NULL,
  "nilai_akhir" decimal(5,2) DEFAULT null,
  "jumlah_benar" int DEFAULT null,
  "total_soal" int DEFAULT null,
  "status" test_session_status_enum NOT NULL DEFAULT 'ongoing',
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "test_session_soal" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_test_session" int NOT NULL,
  "id_soal" int DEFAULT null,
  "question_type" test_session_soal_question_type_enum NOT NULL DEFAULT 'multiple_choice',
  "id_soal_drag_drop" int DEFAULT null,
  "nomor_urut" smallint NOT NULL
);

CREATE TABLE "tingkat" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nama" varchar(50) NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "user_limit_usage" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" int NOT NULL,
  "limit_type" varchar(100) NOT NULL,
  "action" varchar(100) NOT NULL,
  "resource_id" int DEFAULT null,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "user_limits" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" int NOT NULL,
  "limit_type" varchar(100) NOT NULL,
  "limit_value" int NOT NULL DEFAULT '0',
  "current_used" int NOT NULL DEFAULT '0',
  "reset_at" timestamp NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "email" varchar(100) NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "nama" varchar(100) NOT NULL,
  "role" users_role_enum NOT NULL DEFAULT 'siswa',
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE UNIQUE INDEX "idx_drag_correct_item_slot" ON "drag_correct_answer" ("id_drag_item", "id_drag_slot");

CREATE INDEX "idx_drag_correct_item" ON "drag_correct_answer" ("id_drag_item");

CREATE INDEX "idx_drag_correct_slot" ON "drag_correct_answer" ("id_drag_slot");

CREATE INDEX "idx_drag_correct_answer_item" ON "drag_correct_answer" ("id_drag_item");

CREATE INDEX "idx_drag_correct_answer_slot" ON "drag_correct_answer" ("id_drag_slot");

CREATE INDEX "idx_drag_correct_answer_item_slot" ON "drag_correct_answer" ("id_drag_item", "id_drag_slot");

CREATE INDEX "idx_drag_correct_answer_soal_query" ON "drag_correct_answer" ("id_drag_item");

CREATE INDEX "idx_drag_item_soal" ON "drag_item" ("id_soal_drag_drop");

CREATE INDEX "idx_drag_item_urutan" ON "drag_item" ("id_soal_drag_drop", "urutan");

CREATE INDEX "idx_drag_item_soal_id" ON "drag_item" ("id_soal_drag_drop");

CREATE INDEX "idx_drag_item_soal_urutan" ON "drag_item" ("id_soal_drag_drop", "urutan");

CREATE INDEX "idx_drag_slot_soal" ON "drag_slot" ("id_soal_drag_drop");

CREATE INDEX "idx_drag_slot_urutan" ON "drag_slot" ("id_soal_drag_drop", "urutan");

CREATE INDEX "idx_drag_slot_soal_id" ON "drag_slot" ("id_soal_drag_drop");

CREATE INDEX "idx_drag_slot_soal_urutan" ON "drag_slot" ("id_soal_drag_drop", "urutan");

CREATE INDEX "idx_drag_slot_urutan_updated" ON "drag_slot" ("id_soal_drag_drop", "urutan");

CREATE UNIQUE INDEX "idx_jawaban_siswa_unique" ON "jawaban_siswa" ("id_test_session_soal");

CREATE INDEX "idx_jawaban_siswa_is_correct" ON "jawaban_siswa" ("is_correct");

CREATE INDEX "idx_jawaban_siswa_dijawab_pada" ON "jawaban_siswa" ("dijawab_pada");

CREATE INDEX "idx_jawaban_siswa_type" ON "jawaban_siswa" ("question_type");

CREATE UNIQUE INDEX "idx_mata_pelajaran_nama" ON "mata_pelajaran" ("nama");

CREATE INDEX "idx_mata_pelajaran_is_active" ON "mata_pelajaran" ("is_active");

CREATE INDEX "idx_mata_pelajaran_active" ON "mata_pelajaran" ("is_active");

CREATE UNIQUE INDEX "idx_materi_unique" ON "materi" ("id_mata_pelajaran", "id_tingkat", "nama");

CREATE INDEX "idx_materi_mata_pelajaran" ON "materi" ("id_mata_pelajaran");

CREATE INDEX "idx_materi_tingkat" ON "materi" ("id_tingkat");

CREATE INDEX "idx_materi_is_active" ON "materi" ("is_active");

CREATE INDEX "idx_materi_active_tingkat" ON "materi" ("is_active", "id_tingkat");

CREATE INDEX "idx_materi_active_mata_pelajaran" ON "materi" ("is_active", "id_mata_pelajaran");

CREATE INDEX "idx_materi_composite" ON "materi" ("id_mata_pelajaran", "id_tingkat", "is_active");

CREATE INDEX "idx_materi_active" ON "materi" ("is_active");

CREATE INDEX "idx_materi_school" ON "materi" ("school_id");

CREATE INDEX "idx_materi_owner_user" ON "materi" ("owner_user_id");

CREATE INDEX "idx_soal_materi" ON "soal" ("id_materi");

CREATE INDEX "idx_soal_tingkat" ON "soal" ("id_tingkat");

CREATE INDEX "idx_soal_is_active" ON "soal" ("is_active");

CREATE INDEX "idx_soal_active_materi" ON "soal" ("is_active", "id_materi");

CREATE INDEX "idx_soal_active_tingkat" ON "soal" ("is_active", "id_tingkat");

CREATE INDEX "idx_soal_materi_active" ON "soal" ("id_materi", "is_active");

CREATE INDEX "idx_soal_created_at" ON "soal" ("created_at");

CREATE INDEX "idx_soal_drag_drop_materi" ON "soal_drag_drop" ("id_materi");

CREATE INDEX "idx_soal_drag_drop_tingkat" ON "soal_drag_drop" ("id_tingkat");

CREATE INDEX "idx_soal_drag_drop_is_active" ON "soal_drag_drop" ("is_active");

CREATE INDEX "idx_soal_drag_drop_type" ON "soal_drag_drop" ("drag_type");

CREATE INDEX "idx_soal_drag_drop_active_materi" ON "soal_drag_drop" ("is_active", "id_materi");

CREATE INDEX "idx_soal_drag_drop_active_tingkat" ON "soal_drag_drop" ("is_active", "id_tingkat");

CREATE INDEX "idx_soal_drag_drop_gambar_soal" ON "soal_drag_drop_gambar" ("id_soal_drag_drop");

CREATE INDEX "idx_soal_gambar_soal" ON "soal_gambar" ("id_soal");

CREATE INDEX "idx_soal_gambar_soal_urutan" ON "soal_gambar" ("id_soal", "urutan");

CREATE INDEX "idx_soal_gambar_cloud_id" ON "soal_gambar" ("cloud_id");

CREATE INDEX "idx_soal_gambar_public_id" ON "soal_gambar" ("public_id");

CREATE UNIQUE INDEX "idx_test_session_token" ON "test_session" ("session_token");

CREATE INDEX "idx_test_session_tingkat" ON "test_session" ("id_tingkat");

CREATE INDEX "idx_test_session_mata_pelajaran" ON "test_session" ("id_mata_pelajaran");

CREATE INDEX "idx_test_session_user" ON "test_session" ("user_id");

CREATE INDEX "idx_test_session_waktu_mulai" ON "test_session" ("waktu_mulai");

CREATE INDEX "idx_test_session_status" ON "test_session" ("status");

CREATE INDEX "idx_test_session_user_status" ON "test_session" ("user_id", "status");

CREATE INDEX "idx_test_session_status_waktu" ON "test_session" ("status", "waktu_mulai");

CREATE UNIQUE INDEX "idx_test_session_soal_unique" ON "test_session_soal" ("id_test_session", "nomor_urut");

CREATE INDEX "idx_test_session_soal_session" ON "test_session_soal" ("id_test_session");

CREATE INDEX "idx_test_session_soal_soal" ON "test_session_soal" ("id_soal");

CREATE INDEX "idx_test_session_soal_type" ON "test_session_soal" ("question_type");

CREATE INDEX "idx_test_session_soal_drag_drop" ON "test_session_soal" ("id_soal_drag_drop");

CREATE UNIQUE INDEX "idx_tingkat_nama" ON "tingkat" ("nama");

CREATE INDEX "idx_tingkat_is_active" ON "tingkat" ("is_active");

CREATE INDEX "idx_tingkat_active" ON "tingkat" ("is_active");

CREATE INDEX "idx_user_limit_usage_user" ON "user_limit_usage" ("user_id");

CREATE INDEX "idx_user_limit_usage_type" ON "user_limit_usage" ("limit_type");

CREATE INDEX "idx_user_limit_usage_created_at" ON "user_limit_usage" ("created_at");

CREATE INDEX "idx_user_limit_usage_resource_id" ON "user_limit_usage" ("resource_id");

CREATE INDEX "idx_user_limit_usage_user_created" ON "user_limit_usage" ("user_id", "created_at");

CREATE INDEX "idx_user_limit_usage_user_type_created" ON "user_limit_usage" ("user_id", "limit_type", "created_at");

CREATE UNIQUE INDEX "idx_user_limits_unique" ON "user_limits" ("user_id", "limit_type");

CREATE INDEX "idx_user_limits_user" ON "user_limits" ("user_id");

CREATE INDEX "idx_user_limits_reset_at" ON "user_limits" ("reset_at");

CREATE INDEX "idx_user_limits_user_type" ON "user_limits" ("user_id", "limit_type");

CREATE INDEX "idx_user_limits_type_reset" ON "user_limits" ("limit_type", "reset_at");

CREATE UNIQUE INDEX "idx_users_email" ON "users" ("email");

CREATE INDEX "idx_users_role" ON "users" ("role");

CREATE INDEX "idx_users_is_active" ON "users" ("is_active");

CREATE INDEX "idx_users_active_role" ON "users" ("is_active", "role");

CREATE INDEX "idx_users_created_at" ON "users" ("created_at");

COMMENT ON TABLE "drag_correct_answer" IS 'Correct answer mapping: which item goes to which slot';

COMMENT ON TABLE "drag_item" IS 'Draggable items for drag-drop questions';

COMMENT ON COLUMN "drag_item"."label" IS 'Text label for the item';

COMMENT ON COLUMN "drag_item"."image_url" IS 'Optional image URL (Cloudinary)';

COMMENT ON COLUMN "drag_item"."urutan" IS 'Display order';

COMMENT ON TABLE "drag_slot" IS 'Drop zones/slots for drag-drop questions';

COMMENT ON COLUMN "drag_slot"."label" IS 'Slot label (1,2,3 or category name)';

COMMENT ON COLUMN "drag_slot"."image_url" IS 'Optional image URL for slot (Cloudinary)';

COMMENT ON COLUMN "drag_slot"."urutan" IS 'Display order';

COMMENT ON TABLE "jawaban_siswa" IS 'Student answers for test questions';

COMMENT ON COLUMN "jawaban_siswa"."jawaban_dipilih" IS 'Selected answer (A/B/C/D)';

COMMENT ON COLUMN "jawaban_siswa"."question_type" IS 'Type of question answered';

COMMENT ON COLUMN "jawaban_siswa"."jawaban_drag_drop" IS 'Drag-drop answer: {"item_id": slot_id, ...}';

COMMENT ON TABLE "mata_pelajaran" IS 'Subject/Course master data';

COMMENT ON TABLE "materi" IS 'Learning materials/topics with test configuration';

COMMENT ON TABLE "soal" IS 'Test questions with multiple choice answers';

COMMENT ON COLUMN "soal"."pembahasan" IS 'Answer explanation';

COMMENT ON COLUMN "soal"."image_path" IS 'Legacy filesystem path';

COMMENT ON TABLE "soal_drag_drop" IS 'Drag and drop questions (ordering/matching types)';

COMMENT ON COLUMN "soal_drag_drop"."drag_type" IS 'ordering=sequence, matching=categorize';

COMMENT ON COLUMN "soal_drag_drop"."pembahasan" IS 'Answer explanation';

COMMENT ON TABLE "soal_gambar" IS 'Question images metadata (Cloudinary storage)';

COMMENT ON COLUMN "soal_gambar"."nama_file" IS 'Original filename';

COMMENT ON COLUMN "soal_gambar"."file_path" IS 'Relative path from storage root';

COMMENT ON COLUMN "soal_gambar"."file_size" IS 'File size in bytes';

COMMENT ON COLUMN "soal_gambar"."mime_type" IS 'image/jpeg, image/png, etc';

COMMENT ON COLUMN "soal_gambar"."urutan" IS 'Order for multiple images';

COMMENT ON COLUMN "soal_gambar"."keterangan" IS 'Image description/caption';

COMMENT ON COLUMN "soal_gambar"."cloud_id" IS 'Cloudinary resource ID';

COMMENT ON COLUMN "soal_gambar"."public_id" IS 'Cloudinary public ID';

COMMENT ON TABLE "test_session" IS 'Test/exam sessions';

COMMENT ON COLUMN "test_session"."user_id" IS 'Linked user (NULL for anonymous)';

COMMENT ON TABLE "test_session_soal" IS 'Questions assigned to test sessions';

COMMENT ON COLUMN "test_session_soal"."id_soal" IS 'FK to soal for multiple choice questions (NULL for drag-drop)';

COMMENT ON COLUMN "test_session_soal"."question_type" IS 'Type of question';

COMMENT ON COLUMN "test_session_soal"."id_soal_drag_drop" IS 'FK to soal_drag_drop for drag-drop questions';

COMMENT ON TABLE "tingkat" IS 'Grade/level master data';

COMMENT ON TABLE "user_limit_usage" IS 'Usage tracking for limits';

COMMENT ON COLUMN "user_limit_usage"."action" IS 'Action performed';

COMMENT ON COLUMN "user_limit_usage"."resource_id" IS 'Related resource ID';

COMMENT ON TABLE "user_limits" IS 'User usage limits and quotas';

COMMENT ON COLUMN "user_limits"."limit_type" IS 'api_requests_per_hour, test_sessions_per_day, etc';

COMMENT ON TABLE "users" IS 'User authentication and authorization';

COMMENT ON COLUMN "users"."password_hash" IS 'Bcrypt hashed password';

ALTER TABLE "drag_correct_answer" ADD CONSTRAINT "fk_drag_correct_item" FOREIGN KEY ("id_drag_item") REFERENCES "drag_item" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "drag_correct_answer" ADD CONSTRAINT "fk_drag_correct_slot" FOREIGN KEY ("id_drag_slot") REFERENCES "drag_slot" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "drag_item" ADD CONSTRAINT "fk_drag_item_soal" FOREIGN KEY ("id_soal_drag_drop") REFERENCES "soal_drag_drop" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "drag_slot" ADD CONSTRAINT "fk_drag_slot_soal" FOREIGN KEY ("id_soal_drag_drop") REFERENCES "soal_drag_drop" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "jawaban_siswa" ADD CONSTRAINT "fk_jawaban_siswa_test_session_soal" FOREIGN KEY ("id_test_session_soal") REFERENCES "test_session_soal" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "materi" ADD CONSTRAINT "fk_materi_mata_pelajaran" FOREIGN KEY ("id_mata_pelajaran") REFERENCES "mata_pelajaran" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "materi" ADD CONSTRAINT "fk_materi_tingkat" FOREIGN KEY ("id_tingkat") REFERENCES "tingkat" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "soal" ADD CONSTRAINT "fk_soal_materi" FOREIGN KEY ("id_materi") REFERENCES "materi" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "soal" ADD CONSTRAINT "fk_soal_tingkat" FOREIGN KEY ("id_tingkat") REFERENCES "tingkat" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "soal_drag_drop" ADD CONSTRAINT "fk_soal_drag_drop_materi" FOREIGN KEY ("id_materi") REFERENCES "materi" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "soal_drag_drop" ADD CONSTRAINT "fk_soal_drag_drop_tingkat" FOREIGN KEY ("id_tingkat") REFERENCES "tingkat" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "soal_drag_drop_gambar" ADD CONSTRAINT "fk_soal_drag_drop_gambar_soal" FOREIGN KEY ("id_soal_drag_drop") REFERENCES "soal_drag_drop" ("id") ON DELETE CASCADE;

ALTER TABLE "soal_gambar" ADD CONSTRAINT "fk_soal_gambar_soal" FOREIGN KEY ("id_soal") REFERENCES "soal" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "test_session" ADD CONSTRAINT "fk_test_session_mata_pelajaran" FOREIGN KEY ("id_mata_pelajaran") REFERENCES "mata_pelajaran" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "test_session" ADD CONSTRAINT "fk_test_session_tingkat" FOREIGN KEY ("id_tingkat") REFERENCES "tingkat" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "test_session" ADD CONSTRAINT "fk_test_session_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "test_session_soal" ADD CONSTRAINT "fk_test_session_soal_drag_drop" FOREIGN KEY ("id_soal_drag_drop") REFERENCES "soal_drag_drop" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "test_session_soal" ADD CONSTRAINT "fk_test_session_soal_session" FOREIGN KEY ("id_test_session") REFERENCES "test_session" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "test_session_soal" ADD CONSTRAINT "fk_test_session_soal_soal" FOREIGN KEY ("id_soal") REFERENCES "soal" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "user_limit_usage" ADD CONSTRAINT "fk_user_limit_usage_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "user_limits" ADD CONSTRAINT "fk_user_limits_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
